name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install git+https://github.com/adblockplus/python-abp.git@4b0aec2
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global push.default "matching"
    
    - name: Clone output repository
      run: |
        git clone --depth=3 -b gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/easylist/easylist" output
    
    - name: Generate filter lists
      run: |
        flrender -i easylist=. easylist.template output/easylist.txt
        flrender -i easylist=. easyprivacy.template output/easyprivacy.txt
        flrender -i easylist=. fanboy-social.template output/fanboy-social.txt
        flrender -i easylist=. fanboy-annoyance.template output/fanboy-annoyance.txt 
        flrender -i easylist=. fanboy-newsletter.template output/fanboy-newsletter.txt
        flrender -i easylist=. fanboy-sounds.template output/fanboy-sounds.txt
    
    - name: Add verification metadata
      run: |
        for file in output/*.txt; do
          temp_file=$(mktemp)
          echo "! Repository: ${{ github.repository }}" > "$temp_file"
          echo "! Commit: ${{ github.sha }}" >> "$temp_file"
          echo "! Built: $(date -u)" >> "$temp_file"
          echo "! Official: https://github.com/easylist/easylist" >> "$temp_file"
          echo "!" >> "$temp_file"
          cat "$file" >> "$temp_file"
          mv "$temp_file" "$file"
        done
    
    - name: Commit and push changes
      run: |
        cd output
        echo "Current directory: $(pwd)"
        echo "Git status before add:"
        git status
        git add --all .
        echo "Git status after add:"
        git status
        git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)"
        echo "Attempting to push to remote..."
        git remote -v
        git push --force origin gh-pages
